language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer install
  - php artisan migrate --force
  - php artisan db:seed --force
  - php artisan vendor:publish --provider="Owl\Providers\TwitterBootstrapServiceProvider"
  - vendor/bin/behat --colors
